version: '3.8'

services:
  database:
    extends:
      file: docker-compose.yml
      service: database

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  celery:
    extends:
      file: docker-compose.yml
      service: celery

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    command: bash -c 'gunicorn --bind 0.0.0.0:9000 contana.wsgi'


volumes:
  postgres_data:
