version: '3.8'

services:
  database:
    extends:
      file: docker-compose.yml
      service: database

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  celery:
    extends:
      file: docker-compose.yml
      service: celery
    depends_on:
        - redis
        - database

  celery_beat:
    extends:
      file: docker-compose.yml
      service: celery_beat
    depends_on:
        - redis
        - database

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    command: bash -c 'gunicorn --bind 0.0.0.0:9000 contana.wsgi'
    ports:
      - "9000:9000"
    depends_on:
        - database


volumes:
  postgres_data:
