version: '3.8'

services:
  database:
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./backend/.env

  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    restart: unless-stopped
    image: "${BACKEND_IMAGE}"
    command: bash -c 'while !</dev/tcp/redis/6379; do sleep 1; done; celery -A contana worker -l info'
    depends_on:
      - redis
      - database
    env_file:
      - ./backend/.env

  celery_beat:
    restart: unless-stopped
    image: "${BACKEND_IMAGE}"
    command: bash -c 'while !</dev/tcp/redis/6379; do sleep 1; done; celery -A contana beat -l info'
    depends_on:
      - redis
      - database
    env_file:
      - ./backend/.env


  backend:
    restart: unless-stopped
    image: "${BACKEND_IMAGE}"
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c 'gunicorn --bind 0.0.0.0:9000 contana.wsgi'
    ports:
      - "9000:9000"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/static:/app/static


volumes:
  postgres_data:
