from django.urls import path

from .views import views
from .views import stripe as stripe_views

urlpatterns = [
    path(
        "api/entreprise/<str:entreprise_slug>/data",
        views.get_data,
        name="get_data",
    ),
    path(
        "api/entreprise/create-checkout-session",
        stripe_views.create_entreprise_checkout_session,
        name="create_entreprise_checkout_session",
    ),
    path(
        "api/entreprise/stripe-subscription-webhook",
        stripe_views.stripe_entreprise_subscription_webhook,
        name="stripe_entreprise_subscription_webhook",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/informations",
        views.update_entreprise_informations,
        name="update_entreprise_informations",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/informations/personnalization/documents",
        views.update_entreprise_document_personalisation,
        name="update_entreprise_document_personalisation",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/informations/personnalization/documents/preview",
        views.get_document_personnalization_preview,
        name="get_document_personnalization_preview",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/delete",
        views.delete_entreprise,
        name="delete_entreprise",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/logos",
        views.update_entreprise_logos,
        name="update_entreprise_logos",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/user/<int:user_id>/permissions",
        views.update_entreprise_user_permissions,
        name="update_entreprise_user_permissions",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/user/<int:user_id>/remove",
        views.remove_user_from_entreprise,
        name="remove_user_from_entreprise",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/invitations/create",
        views.create_invitation_link,
        name="create_invitation_link",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/invitations/send-by-email",
        views.send_invitation_link_by_email,
        name="send_invitation_link_by_email",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/invitations/get-info",
        views.get_invitation_link_info,
        name="get_invitation_link_info",
    ),
    path(
        "api/entreprise/<str:entreprise_slug>/settings/invitations/join",
        views.join_entreprise,
        name="join_entreprise",
    ),
]
