# Generated by Django 4.2.1 on 2025-01-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
