# Generated by Django 4.2.1 on 2025-01-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_client_status"),
        ("tasks", "0003_task_entreprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="clients.client",
            ),
        ),
    ]
