# Generated by Django 4.2.1 on 2025-01-19 10:07

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_task_client"),
    ]

    operations = [UnaccentExtension()]
