# Generated by Django 4.2.1 on 2025-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_auto_20250119_1007"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
