# Generated by Django 4.2.1 on 2023-05-28 13:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="name", unique=True
            ),
        ),
    ]
