# Generated by Django 4.2.1 on 2023-05-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entreprise", "0002_entreprise_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="users",
            field=models.ManyToManyField(
                related_name="entreprises", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_entreprises",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
