# Generated by Django 4.2.1 on 2023-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0003_entreprise_users_alter_entreprise_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="ape",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="bank",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="bic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="capital",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="forme",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="iban",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="num_rcs",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="num_tva_intracom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="phone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="siret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="zip_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
