# Generated by Django 4.2.1 on 2023-06-04 17:30

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "entreprise",
            "0004_entreprise_address_entreprise_ape_entreprise_bank_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="EntrepriseLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.ImageField(upload_to="entreprises/logos/")),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entreprise_logos",
                        to="entreprise.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
