# Generated by Django 4.2.1 on 2023-06-15 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0005_alter_entreprise_slug_entrepriselogo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entreprise",
            options={
                "permissions": (
                    ("access_documents", "Allows to access the documents"),
                    ("update_documents", "Allows to update the documents"),
                    ("access_clients", "Allows to access the clients"),
                    ("update_clients", "Allows to update the clients"),
                    ("access_constructeur", "Allows to access the constructeur"),
                )
            },
        ),
    ]
