# Generated by Django 4.2.1 on 2023-07-08 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0008_invitationslink"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitationslink",
            old_name="access_link",
            new_name="token",
        ),
    ]
