# Generated by Django 4.2.1 on 2023-07-08 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0009_rename_access_link_invitationslink_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entreprise",
            options={
                "permissions": (
                    ("administrate", "Allows to administrate the entreprise"),
                    ("access_documents", "Allows to access the documents"),
                    ("update_documents", "Allows to update the documents"),
                    ("access_clients", "Allows to access the clients"),
                    ("update_clients", "Allows to update the clients"),
                    ("access_constructor", "Allows to access the constructeur"),
                )
            },
        ),
    ]
