# Generated by Django 4.2.1 on 2023-07-08 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entreprise", "0010_alter_entreprise_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationslink",
            name="used_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_invitations_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
