# Generated by Django 4.2.1 on 2023-07-19 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0011_invitationslink_used_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entreprise",
            old_name="num_tva_intracom",
            new_name="vat_number",
        ),
    ]
