# Generated by Django 4.2.1 on 2023-08-07 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0012_rename_num_tva_intracom_entreprise_vat_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entreprise",
            old_name="siret",
            new_name="siren",
        ),
    ]
