# Generated by Django 4.2.1 on 2023-08-16 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0013_rename_siret_entreprise_siren"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entreprise",
            old_name="siren",
            new_name="siret",
        ),
    ]
