# Generated by Django 4.2.1 on 2023-10-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0015_rename_siret_entreprise_siren"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="document_default_payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Virement bancaire"),
                    ("check", "Chèque"),
                    ("cash", "Espèce"),
                    ("credit_card", "Carte bancaire"),
                    ("direct_debit", "Prélèvement automatique"),
                    ("other", "Autre"),
                ],
                default="bank_transfer",
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="document_logo_margin_bottom",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="document_logo_margin_right",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="document_logo_margin_top",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="document_logo_size",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="document_logo_used",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_by",
                to="entreprise.entrepriselogo",
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="document_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="document_other_mention",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="document_payment_mention",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="vat_payer",
            field=models.BooleanField(default=True),
        ),
    ]
