# Generated by Django 4.2.1 on 2023-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0016_entreprise_document_default_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="document_other_mention",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="document_payment_mention",
            field=models.CharField(blank=True, null=True),
        ),
    ]
