# Generated by Django 4.2.1 on 2023-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0017_alter_entreprise_document_other_mention_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="address",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="ape",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="bank",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="bic",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="capital",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="city",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="country",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="forme",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="iban",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="num_rcs",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="phone",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="siren",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="vat_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="zip_code",
            field=models.CharField(blank=True, null=True),
        ),
    ]
