# Generated by Django 4.2.1 on 2023-10-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0018_alter_entreprise_address_alter_entreprise_ape_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="document_notes",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="document_other_mention",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="document_payment_mention",
            field=models.CharField(blank=True, default=""),
        ),
    ]
