# Generated by Django 4.2.1 on 2023-10-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0019_alter_entreprise_document_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="document_notes",
            field=models.TextField(
                blank=True,
                default="En cas de retard de paiement, il sera appliqué des pénalités et intérêts de retard suivant le taux minimum légal en vigueur, par mois de retard. En outre, une indemnité forfaitaire pour frais de recouvrement de 40€ sera due.",
            ),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="document_payment_mention",
            field=models.CharField(blank=True, default="À réception de la facture"),
        ),
    ]
