# Generated by Django 4.2.1 on 2024-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0022_entreprise_first_acompte_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="first_client_number",
            field=models.IntegerField(default=1),
        ),
    ]
