# Generated by Django 4.2.1 on 2024-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0023_entreprise_first_client_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="address",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="ape",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="bank",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="bic",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="capital",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="city",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="country",
            field=models.CharField(blank=True, default="France", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="forme",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="iban",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="num_rcs",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="phone",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="siren",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="vat_number",
            field=models.CharField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="entreprise",
            name="zip_code",
            field=models.CharField(blank=True, default="", null=True),
        ),
    ]
