# Generated by Django 4.2.1 on 2024-02-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0025_entreprisecheckoutsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="stripe_customer_id",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="stripe_payment_status",
            field=models.CharField(
                blank=True, choices=[("paid", "Paid"), ("failed", "Failed")]
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="stripe_subscription_id",
            field=models.CharField(blank=True),
        ),
    ]
