# Generated by Django 4.2.1 on 2024-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0026_entreprise_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entreprise",
            name="stripe_payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
            ),
        ),
    ]
