# Generated by Django 4.2.1 on 2025-11-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0029_applicationtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtoken",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Name"),
        ),
    ]
