# Generated by Django 4.2.1 on 2025-11-02 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0030_applicationtoken_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationtoken",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="applicationtoken",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
