# Generated by Django 4.2.1 on 2025-11-02 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0031_applicationtoken_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationtoken",
            name="last_used",
        ),
    ]
