# Generated by Django 4.2.1 on 2025-11-02 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0032_remove_applicationtoken_last_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationtoken",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="applicationtoken",
            name="updated_at",
        ),
    ]
