# Generated by Django 4.2.1 on 2023-07-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("particulier", "Particulier"),
                    ("professionnel", "Professionnel"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
