# Generated by Django 4.2.1 on 2023-07-29 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_client_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="clients/files")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
