# Generated by Django 4.2.1 on 2023-08-16 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_rename_siret_client_siren"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="siren",
            new_name="siret",
        ),
    ]
