# Generated by Django 4.2.1 on 2023-08-27 18:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0006_rename_siren_client_siret"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="siret",
            new_name="siren",
        ),
    ]
