# Generated by Django 4.2.1 on 2025-01-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0008_client_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Actif"),
                    ("lead", "Lead"),
                    ("first_relaunch", "Premier relance"),
                    ("second_relaunch", "Deuxième relance"),
                    ("third_relaunch", "Troisième relance"),
                    ("long_term_relaunch", "Relance long terme"),
                    ("inactive", "Inactif"),
                ],
                default="lead",
                max_length=255,
            ),
        ),
    ]
