# Generated by Django 4.2.1 on 2025-11-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_client_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="crm_platform",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="crm_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="crm_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
