# Generated by Django 4.2.1 on 2025-11-01 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0010_client_platform_client_source_client_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="platform",
            new_name="crm_platform",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="source",
            new_name="crm_source",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="url",
            new_name="crm_url",
        ),
    ]
