# Generated by Django 4.2.1 on 2025-11-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0010_client_crm_platform_client_crm_source_client_crm_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("suspect", "Suspect"),
                    ("prospect", "Prospect"),
                    ("client", "Client"),
                    ("archived", "Archivé"),
                ],
                default="suspect",
                max_length=255,
            ),
        ),
    ]
