# Generated by Django 4.2.1 on 2025-11-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0011_alter_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.CharField(
                blank=True, default="France", max_length=255, null=True
            ),
        ),
    ]
