# Generated by Django 4.2.1 on 2023-08-21 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="total_vat",
            new_name="total_tva",
        ),
    ]
