# Generated by Django 4.2.1 on 2023-08-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_rename_total_vat_document_total_tva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsection",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="documentsection",
            name="discount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="documentsection",
            name="discount_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="documentsection",
            name="quantity",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="documentsection",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="documentsection",
            name="unit_price_ht",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="documentsection",
            name="vat_rate",
            field=models.FloatField(default=20),
        ),
    ]
