# Generated by Django 4.2.1 on 2023-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_alter_documentsection_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsection",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("percentage", "Pourcentage"), ("amount", "Montant")],
            ),
        ),
    ]
