# Generated by Django 4.2.1 on 2023-08-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_alter_documentsection_discount_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("produced", "Produit"),
                    ("devis_accepted", "Devis accepté"),
                    ("devis_refused", "Devis refusé"),
                    ("devis_expired", "Devis expiré"),
                    ("devis_invoiced", "Devis facturé"),
                    ("paid", "Facture ou acompte payée"),
                ],
                default="draft",
            ),
        ),
    ]
