# Generated by Django 4.2.1 on 2023-08-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_document_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="devis_accepted_or_refused_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
