# Generated by Django 4.2.1 on 2023-08-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_document_devis_accepted_or_refused_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="linked_devis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_facture",
                to="documents.document",
            ),
        ),
    ]
