# Generated by Django 4.2.1 on 2023-08-26 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0008_document_linked_devis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="linked_devis",
        ),
        migrations.AddField(
            model_name="document",
            name="linked_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.document",
            ),
        ),
    ]
