# Generated by Django 4.2.1 on 2023-08-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_remove_document_linked_devis_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="linked_document",
        ),
        migrations.AddField(
            model_name="document",
            name="linked_devis",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_facture",
                to="documents.document",
            ),
        ),
    ]
