# Generated by Django 4.2.1 on 2023-09-18 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_remove_document_linked_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="linked_parent_devis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_acomptes",
                to="documents.document",
            ),
        ),
    ]
