# Generated by Django 4.2.1 on 2023-09-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0011_document_linked_parent_devis"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="linked_parent_facture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_avoirs",
                to="documents.document",
            ),
        ),
    ]
