# Generated by Django 4.2.1 on 2023-09-23 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0015_rename_siret_entreprise_siren"),
        ("documents", "0012_document_linked_parent_facture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsection",
            name="document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="documents.document",
            ),
        ),
        migrations.CreateModel(
            name="TemplateCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "entreprise",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_categories",
                        to="entreprise.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SectionsTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="documents.templatecategories",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="entreprise.entreprise",
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        blank=True,
                        related_name="templates",
                        to="documents.documentsection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
