# Generated by Django 4.2.1 on 2023-09-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0013_alter_documentsection_document_templatecategories_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsection",
            name="subtotal",
            field=models.FloatField(default=0),
        ),
    ]
