# Generated by Django 4.2.1 on 2023-09-23 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0014_documentsection_subtotal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionstemplate",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="documents.templatecategories",
            ),
        ),
    ]
