# Generated by Django 4.2.1 on 2023-09-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0015_alter_sectionstemplate_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionstemplate",
            name="sections",
        ),
        migrations.AddField(
            model_name="sectionstemplate",
            name="article",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template",
                to="documents.documentsection",
            ),
        ),
    ]
