# Generated by Django 4.2.1 on 2023-09-23 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0015_rename_siret_entreprise_siren"),
        ("documents", "0016_remove_sectionstemplate_sections_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "article",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="documents.documentsection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="TemplateCategories",
            new_name="TemplateCategory",
        ),
        migrations.DeleteModel(
            name="SectionsTemplate",
        ),
        migrations.AddField(
            model_name="template",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="documents.templatecategory",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="entreprise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="entreprise.entreprise",
            ),
        ),
    ]
