# Generated by Django 4.2.1 on 2023-09-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0017_template_rename_templatecategories_templatecategory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="documents.templatecategory",
            ),
        ),
    ]
