# Generated by Django 4.2.1 on 2023-10-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0018_alter_template_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsection",
            name="total_ht",
            field=models.FloatField(default=0),
        ),
    ]
