# Generated by Django 4.2.1 on 2023-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0019_documentsection_total_ht"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsection",
            name="total_ht_without_discount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="documentsection",
            name="unit",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("mm", "mm"),
                    ("cm", "cm"),
                    ("m", "m"),
                    ("km", "km"),
                    ("m²", "m²"),
                    ("m³", "m³"),
                    ("kg", "kg"),
                    ("hour", "heure(s)"),
                    ("day", "jour(s)"),
                    ("month", "mois"),
                    ("year", "année(s)"),
                    ("ml", "ml"),
                    ("l", "l"),
                ],
                default="",
            ),
        ),
    ]
