# Generated by Django 4.2.1 on 2023-10-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0020_documentsection_total_ht_without_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents"),
        ),
    ]
