# Generated by Django 4.2.1 on 2023-11-01 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("entreprise", "0020_alter_entreprise_document_notes_and_more"),
        ("documents", "0022_alter_document_forme"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsection",
            name="entreprise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="entreprise.entreprise",
            ),
        ),
    ]
