# Generated by Django 4.2.1 on 2025-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0024_alter_documentsection_entreprise"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentsection",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="documentsection",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="document-sections/images"
            ),
        ),
    ]
