# Generated by Django 5.2.5 on 2025-08-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0024_alter_documentsection_entreprise"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentsection",
            options={"ordering": ["id"]},
        ),
    ]
