# Generated by Django 4.2.1 on 2025-08-22 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0025_alter_documentsection_options_documentsection_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsection",
            name="image",
        ),
        migrations.CreateModel(
            name="DocumentSectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.ImageField(upload_to="document-sections/images")),
                (
                    "document_sections",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="image",
                        to="documents.documentsection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
