# Generated by Django 4.2.1 on 2025-08-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0026_remove_documentsection_image_documentsectionimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsectionimage",
            name="document_sections",
        ),
        migrations.AddField(
            model_name="documentsection",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="documents.documentsectionimage",
            ),
        ),
    ]
