# Generated by Django 4.2.1 on 2025-11-01 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0025_alter_documentsection_options"),
        ("documents", "0027_remove_documentsectionimage_document_sections_and_more"),
    ]

    operations = []
