# Generated by Django 4.2.1 on 2023-05-22 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(),
                    django.core.validators.MinLengthValidator(30),
                ],
            ),
        ),
    ]
