# Generated by Django 4.2.1 on 2024-05-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
