# Generated by Django 4.2.1 on 2025-11-02 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_applicationtoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationtoken",
            options={
                "ordering": ["-created"],
                "verbose_name": "Application Token",
                "verbose_name_plural": "Application Tokens",
            },
        ),
    ]
