# Generated by Django 4.2.1 on 2025-11-02 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_applicationtoken_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApplicationToken",
        ),
    ]
