name: Deployment Workflow
on: [push]

env:
  BACKEND_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/backend

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo "BACKEND_IMAGE=$(echo ${{env.BACKEND_IMAGE}} )" >> $GITHUB_ENV
      - name: Log in to GitHub Packages
        run: echo ${PERSONAL_ACCESS_TOKEN} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Add environment variables to .env
        run: |
          echo USELESS_VAR=useless_value >> backend/.env
      - name: Pull image
        run: docker pull ${{ env.BACKEND_IMAGE }} || true
      - name: Build image
        run: docker-compose -f docker-compose.prod.yml build --no-cache
      - name: Push image
        run: docker push ${{ env.BACKEND_IMAGE }}

  deploy:
    name: Deploy on server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add environment variables to .env
        run: |
          mkdir -p backend
          echo AWS_SES_ACCESS_KEY_ID=${{ secrets.AWS_SES_ACCESS_KEY_ID }} >> .env
          echo AWS_SES_SECRET_ACCESS_KEY=${{ secrets.AWS_SES_SECRET_ACCESS_KEY }} >> .env
          echo DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} >> .env
          echo S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} >> .env
          echo S3_ENDPOINT=${{ secrets.S3_ENDPOINT }} >> .env
          echo S3_REGION_NAME=${{ secrets.S3_REGION_NAME }} >> .env
          echo S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} >> .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo BACKEND_IMAGE=ghcr.io/0xpierre/contana/backend:latest >> .env
          echo STRIPE_PUBLIC_KEY=${{ secrets.STRIPE_PUBLIC_KEY }} >> .env
          echo STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} >> .env
          echo STRIPE_ENTREPRISE_SUBSCRIPTION_PRICE_ID=${{ secrets.STRIPE_ENTREPRISE_SUBSCRIPTION_PRICE_ID }} >> .env
          echo STRIPE_ENTREPRISE_SUBSCRIPTION_WEBHOOK_SECRET=${{ secrets.STRIPE_ENTREPRISE_SUBSCRIPTION_WEBHOOK_SECRET }} >> .env
          echo BACKUP_S3_BUCKET_NAME=${{ secrets.BACKUP_S3_BUCKET_NAME }} >> .env
          echo ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} >> .env
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
      - name: Deploy to server
        run: |
          echo "Starting deployment..."
          scp -i ~/.ssh/github_actions -o StrictHostKeyChecking=no -r ./.env ./docker-compose.prod.yml 0xpierre@${{ secrets.SERVER_IP }}:/home/0xpierre/apps/Contana  
          ssh -i ~/.ssh/github_actions -o StrictHostKeyChecking=no 0xpierre@${{ secrets.SERVER_IP }} << 'ENDSSH'
            cd /home/0xpierre/apps/Contana
            mkdir -p backend
          
            mv .env backend/.env
            set -a
            source backend/.env
          
            echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
            docker pull ${BACKEND_IMAGE}
            docker compose -f docker-compose.prod.yml up -d --no-deps --force-recreate
            docker compose -f docker-compose.prod.yml exec backend python manage.py migrate
            docker compose -f docker-compose.prod.yml exec backend python manage.py collectstatic --noinput
          ENDSSH
          echo "Deployment completed."
