name: Deployment Workflow
on: [push]

env:
  BACKEND_IMAGE: ghcr.io/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/backend

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo "BACKEND_IMAGE=$(echo ${{env.BACKEND_IMAGE}} )" >> $GITHUB_ENV
      - name: Log in to GitHub Packages
        run: echo ${PERSONAL_ACCESS_TOKEN} | docker login ghcr.io -u ${{ secrets.NAMESPACE }} --password-stdin
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Add environment variables to .env
        run: |
          echo USELESS_VAR=useless_value >> backend/.env
      - name: Pull image
        run: docker pull ${{ env.BACKEND_IMAGE }} || true
      - name: Build image
        run: docker-compose -f docker-compose.prod.yml build
      - name: Push image
        run: docker push ${{ env.BACKEND_IMAGE }}


#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Set up SSH key
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
#      - name: Deploy to server
#        run: |
#          echo "Starting deployment..."
#          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no 0xpierre@host "cd /home/designcise && git pull origin main && <your-other-commands>"
#          echo "Deployment completed."